[project]
name = "contextforge"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "no-acct-journal", email = "arthurshen168@gmail.com" }
]
requires-python = ">=3.12"

dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "loguru>=0.7.3",
    "minio>=7.2.20",
    "modelscope>=1.40.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pymilvus[model]>=3.0.1",
    "python-dotenv>=1.2.3",
    "transformers>=5.17.0",
    "uvicorn[standard]>=0.52.4",
    "flagembedding>=v1.3.5",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "torchaudio>=2.10.0",
    "python-multipart>=0.0.32",
]

[project.scripts]
contextforge = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"

[tool.uv.sources]
# 强制从 NVIDIA 源安装
torch = { index = "pytorch-cuda" }
torchvision = { index = "pytorch-cuda" }
torchaudio = { index = "pytorch-cuda" }

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
